export const START_MIGRATION = 'START_MIGRATION';
export const FINISH_MIGRATION_SUCCESS = 'FINISH_MIGRATION_SUCCESS';
export const FINISH_MIGRATION_ERROR = 'FINISH_MIGRATON_ERROR';
export const RESET_MIGRATION_STATE = 'RESET_MIGRATION_STATE';
