export const SET_PLAYLIST_SOURCE = 'SET_PLAYLIST_SOURCE';
export const UNSET_PLAYLIST_SOURCE = 'UNSET_PLAYLIST_SOURCE';

export const REQUEST_PLAYLISTS = 'REQUEST_PLAYLISTS';
export const REQUEST_PLAYLISTS_SUCCESS = 'REQUEST_PLAYLISTS_SUCCESS';
export const REQUEST_PLAYLISTS_ERROR = 'REQUEST_PLAYLISTS_ERROR';

export const SET_SELECTED_PLAYLIST = 'SET_SELECTED_PLAYLIST';
